### ISSUE TITLE
Static contacts script does not produce hydrogen bonds

### ISSUE THREAD

**Issue by ajvenkat** [akma327/getcontacts#18]
Tried to compute water-mediated interactions from 1U19 crystal structure (input file attached):
`$python static_contacts.py --topology 1U19_A_pdb.txt --output 1U19_test.txt --all-interactions`

But, it appears like no hydrogen bond or water-mediated interactions are being computed:

```
$cat 1U19_test.txt | cut -f2 | sort | uniq
Columns: frame, interaction_type, atom_1, atom_2[, atom_3[, atom_4]]
pc
ps
sb
total_frames:1 interaction_types:sb,pc,ps,ts,vdw,hb,lhb
ts
vdw
```

[1U19_A_pdb.txt](https://github.com/akma327/MDContactNetworks/files/1755411/1U19_A_pdb.txt)

**Comment by ajvenkat** [comment]
Adding hydrogens to the pdb files computes hbss, hbsb and hbbb interactions but no wb or wb2 interactions

**Comment by ajvenkat** [comment]
For static structures, would it be possible to compute hbonds based on distance only, not distance and angle?

**Comment by akma327** [comment]
@ajvenkat When I added a --solv HOH argument then the wb and wb2 contacts were picked up. We'll have to look into setting the defaults for solvent in static computations.

**Comment by ajvenkat** [comment]
Thanks, Anthony!
